# Generated by Django 3.1.1 on 2020-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес филиала')),
                ('working_hours', models.CharField(blank=True, max_length=250, verbose_name='Время работы')),
                ('metro', models.CharField(blank=True, max_length=200, verbose_name='Метро')),
                ('phone_number', models.CharField(blank=True, max_length=250, verbose_name='Номер телефона')),
                ('holiday', models.CharField(blank=True, max_length=250, verbose_name='Отпуск')),
                ('coordinates', models.CharField(blank=True, max_length=250, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['address'],
            },
        ),
    ]
