# Generated by Django 3.1.1 on 2020-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_branch_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='holiday',
            field=models.BooleanField(default=False, verbose_name='Отпуск'),
        ),
    ]
